// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: generic_collection.proto

package cn.leancloud.play.proto;

public interface GenericCollectionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.leancloud.play.proto.GenericCollection)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .cn.leancloud.play.proto.GenericCollectionValue listValue = 1;</code>
   */
  java.util.List<cn.leancloud.play.proto.GenericCollectionValue> 
      getListValueList();
  /**
   * <code>repeated .cn.leancloud.play.proto.GenericCollectionValue listValue = 1;</code>
   */
  cn.leancloud.play.proto.GenericCollectionValue getListValue(int index);
  /**
   * <code>repeated .cn.leancloud.play.proto.GenericCollectionValue listValue = 1;</code>
   */
  int getListValueCount();
  /**
   * <code>repeated .cn.leancloud.play.proto.GenericCollectionValue listValue = 1;</code>
   */
  java.util.List<? extends cn.leancloud.play.proto.GenericCollectionValueOrBuilder> 
      getListValueOrBuilderList();
  /**
   * <code>repeated .cn.leancloud.play.proto.GenericCollectionValue listValue = 1;</code>
   */
  cn.leancloud.play.proto.GenericCollectionValueOrBuilder getListValueOrBuilder(
      int index);

  /**
   * <code>repeated .cn.leancloud.play.proto.GenericCollection.MapEntry mapEntryValue = 2;</code>
   */
  java.util.List<cn.leancloud.play.proto.GenericCollection.MapEntry> 
      getMapEntryValueList();
  /**
   * <code>repeated .cn.leancloud.play.proto.GenericCollection.MapEntry mapEntryValue = 2;</code>
   */
  cn.leancloud.play.proto.GenericCollection.MapEntry getMapEntryValue(int index);
  /**
   * <code>repeated .cn.leancloud.play.proto.GenericCollection.MapEntry mapEntryValue = 2;</code>
   */
  int getMapEntryValueCount();
  /**
   * <code>repeated .cn.leancloud.play.proto.GenericCollection.MapEntry mapEntryValue = 2;</code>
   */
  java.util.List<? extends cn.leancloud.play.proto.GenericCollection.MapEntryOrBuilder> 
      getMapEntryValueOrBuilderList();
  /**
   * <code>repeated .cn.leancloud.play.proto.GenericCollection.MapEntry mapEntryValue = 2;</code>
   */
  cn.leancloud.play.proto.GenericCollection.MapEntryOrBuilder getMapEntryValueOrBuilder(
      int index);
}
