// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: generic_collection.proto

package cn.leancloud.play.proto;

/**
 * Protobuf type {@code cn.leancloud.play.proto.GenericCollection}
 */
public  final class GenericCollection extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cn.leancloud.play.proto.GenericCollection)
    GenericCollectionOrBuilder {
  // Use GenericCollection.newBuilder() to construct.
  private GenericCollection(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GenericCollection() {
    listValue_ = java.util.Collections.emptyList();
    mapEntryValue_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private GenericCollection(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              listValue_ = new java.util.ArrayList<cn.leancloud.play.proto.GenericCollectionValue>();
              mutable_bitField0_ |= 0x00000001;
            }
            listValue_.add(
                input.readMessage(cn.leancloud.play.proto.GenericCollectionValue.parser(), extensionRegistry));
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              mapEntryValue_ = new java.util.ArrayList<cn.leancloud.play.proto.GenericCollection.MapEntry>();
              mutable_bitField0_ |= 0x00000002;
            }
            mapEntryValue_.add(
                input.readMessage(cn.leancloud.play.proto.GenericCollection.MapEntry.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        listValue_ = java.util.Collections.unmodifiableList(listValue_);
      }
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        mapEntryValue_ = java.util.Collections.unmodifiableList(mapEntryValue_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.leancloud.play.proto.GenericCollectionOuterClass.internal_static_cn_leancloud_play_proto_GenericCollection_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.leancloud.play.proto.GenericCollectionOuterClass.internal_static_cn_leancloud_play_proto_GenericCollection_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.leancloud.play.proto.GenericCollection.class, cn.leancloud.play.proto.GenericCollection.Builder.class);
  }

  public interface MapEntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.leancloud.play.proto.GenericCollection.MapEntry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <code>optional string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>optional .cn.leancloud.play.proto.GenericCollectionValue val = 2;</code>
     */
    boolean hasVal();
    /**
     * <code>optional .cn.leancloud.play.proto.GenericCollectionValue val = 2;</code>
     */
    cn.leancloud.play.proto.GenericCollectionValue getVal();
    /**
     * <code>optional .cn.leancloud.play.proto.GenericCollectionValue val = 2;</code>
     */
    cn.leancloud.play.proto.GenericCollectionValueOrBuilder getValOrBuilder();
  }
  /**
   * Protobuf type {@code cn.leancloud.play.proto.GenericCollection.MapEntry}
   */
  public  static final class MapEntry extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.leancloud.play.proto.GenericCollection.MapEntry)
      MapEntryOrBuilder {
    // Use MapEntry.newBuilder() to construct.
    private MapEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MapEntry() {
      key_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MapEntry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              key_ = s;
              break;
            }
            case 18: {
              cn.leancloud.play.proto.GenericCollectionValue.Builder subBuilder = null;
              if (val_ != null) {
                subBuilder = val_.toBuilder();
              }
              val_ = input.readMessage(cn.leancloud.play.proto.GenericCollectionValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(val_);
                val_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.leancloud.play.proto.GenericCollectionOuterClass.internal_static_cn_leancloud_play_proto_GenericCollection_MapEntry_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.leancloud.play.proto.GenericCollectionOuterClass.internal_static_cn_leancloud_play_proto_GenericCollection_MapEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.leancloud.play.proto.GenericCollection.MapEntry.class, cn.leancloud.play.proto.GenericCollection.MapEntry.Builder.class);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    private volatile java.lang.Object key_;
    /**
     * <code>optional string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>optional string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VAL_FIELD_NUMBER = 2;
    private cn.leancloud.play.proto.GenericCollectionValue val_;
    /**
     * <code>optional .cn.leancloud.play.proto.GenericCollectionValue val = 2;</code>
     */
    public boolean hasVal() {
      return val_ != null;
    }
    /**
     * <code>optional .cn.leancloud.play.proto.GenericCollectionValue val = 2;</code>
     */
    public cn.leancloud.play.proto.GenericCollectionValue getVal() {
      return val_ == null ? cn.leancloud.play.proto.GenericCollectionValue.getDefaultInstance() : val_;
    }
    /**
     * <code>optional .cn.leancloud.play.proto.GenericCollectionValue val = 2;</code>
     */
    public cn.leancloud.play.proto.GenericCollectionValueOrBuilder getValOrBuilder() {
      return getVal();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
      }
      if (val_ != null) {
        output.writeMessage(2, getVal());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
      }
      if (val_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getVal());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.leancloud.play.proto.GenericCollection.MapEntry)) {
        return super.equals(obj);
      }
      cn.leancloud.play.proto.GenericCollection.MapEntry other = (cn.leancloud.play.proto.GenericCollection.MapEntry) obj;

      boolean result = true;
      result = result && getKey()
          .equals(other.getKey());
      result = result && (hasVal() == other.hasVal());
      if (hasVal()) {
        result = result && getVal()
            .equals(other.getVal());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      if (hasVal()) {
        hash = (37 * hash) + VAL_FIELD_NUMBER;
        hash = (53 * hash) + getVal().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.leancloud.play.proto.GenericCollection.MapEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.leancloud.play.proto.GenericCollection.MapEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.leancloud.play.proto.GenericCollection.MapEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.leancloud.play.proto.GenericCollection.MapEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.leancloud.play.proto.GenericCollection.MapEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.leancloud.play.proto.GenericCollection.MapEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.leancloud.play.proto.GenericCollection.MapEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.leancloud.play.proto.GenericCollection.MapEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.leancloud.play.proto.GenericCollection.MapEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.leancloud.play.proto.GenericCollection.MapEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.leancloud.play.proto.GenericCollection.MapEntry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.leancloud.play.proto.GenericCollection.MapEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.leancloud.play.proto.GenericCollection.MapEntry)
        cn.leancloud.play.proto.GenericCollection.MapEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.leancloud.play.proto.GenericCollectionOuterClass.internal_static_cn_leancloud_play_proto_GenericCollection_MapEntry_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.leancloud.play.proto.GenericCollectionOuterClass.internal_static_cn_leancloud_play_proto_GenericCollection_MapEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.leancloud.play.proto.GenericCollection.MapEntry.class, cn.leancloud.play.proto.GenericCollection.MapEntry.Builder.class);
      }

      // Construct using cn.leancloud.play.proto.GenericCollection.MapEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        key_ = "";

        if (valBuilder_ == null) {
          val_ = null;
        } else {
          val_ = null;
          valBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.leancloud.play.proto.GenericCollectionOuterClass.internal_static_cn_leancloud_play_proto_GenericCollection_MapEntry_descriptor;
      }

      public cn.leancloud.play.proto.GenericCollection.MapEntry getDefaultInstanceForType() {
        return cn.leancloud.play.proto.GenericCollection.MapEntry.getDefaultInstance();
      }

      public cn.leancloud.play.proto.GenericCollection.MapEntry build() {
        cn.leancloud.play.proto.GenericCollection.MapEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.leancloud.play.proto.GenericCollection.MapEntry buildPartial() {
        cn.leancloud.play.proto.GenericCollection.MapEntry result = new cn.leancloud.play.proto.GenericCollection.MapEntry(this);
        result.key_ = key_;
        if (valBuilder_ == null) {
          result.val_ = val_;
        } else {
          result.val_ = valBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.leancloud.play.proto.GenericCollection.MapEntry) {
          return mergeFrom((cn.leancloud.play.proto.GenericCollection.MapEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.leancloud.play.proto.GenericCollection.MapEntry other) {
        if (other == cn.leancloud.play.proto.GenericCollection.MapEntry.getDefaultInstance()) return this;
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          onChanged();
        }
        if (other.hasVal()) {
          mergeVal(other.getVal());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.leancloud.play.proto.GenericCollection.MapEntry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.leancloud.play.proto.GenericCollection.MapEntry) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>optional string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        key_ = value;
        onChanged();
        return this;
      }

      private cn.leancloud.play.proto.GenericCollectionValue val_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.leancloud.play.proto.GenericCollectionValue, cn.leancloud.play.proto.GenericCollectionValue.Builder, cn.leancloud.play.proto.GenericCollectionValueOrBuilder> valBuilder_;
      /**
       * <code>optional .cn.leancloud.play.proto.GenericCollectionValue val = 2;</code>
       */
      public boolean hasVal() {
        return valBuilder_ != null || val_ != null;
      }
      /**
       * <code>optional .cn.leancloud.play.proto.GenericCollectionValue val = 2;</code>
       */
      public cn.leancloud.play.proto.GenericCollectionValue getVal() {
        if (valBuilder_ == null) {
          return val_ == null ? cn.leancloud.play.proto.GenericCollectionValue.getDefaultInstance() : val_;
        } else {
          return valBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .cn.leancloud.play.proto.GenericCollectionValue val = 2;</code>
       */
      public Builder setVal(cn.leancloud.play.proto.GenericCollectionValue value) {
        if (valBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          val_ = value;
          onChanged();
        } else {
          valBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .cn.leancloud.play.proto.GenericCollectionValue val = 2;</code>
       */
      public Builder setVal(
          cn.leancloud.play.proto.GenericCollectionValue.Builder builderForValue) {
        if (valBuilder_ == null) {
          val_ = builderForValue.build();
          onChanged();
        } else {
          valBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .cn.leancloud.play.proto.GenericCollectionValue val = 2;</code>
       */
      public Builder mergeVal(cn.leancloud.play.proto.GenericCollectionValue value) {
        if (valBuilder_ == null) {
          if (val_ != null) {
            val_ =
              cn.leancloud.play.proto.GenericCollectionValue.newBuilder(val_).mergeFrom(value).buildPartial();
          } else {
            val_ = value;
          }
          onChanged();
        } else {
          valBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .cn.leancloud.play.proto.GenericCollectionValue val = 2;</code>
       */
      public Builder clearVal() {
        if (valBuilder_ == null) {
          val_ = null;
          onChanged();
        } else {
          val_ = null;
          valBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .cn.leancloud.play.proto.GenericCollectionValue val = 2;</code>
       */
      public cn.leancloud.play.proto.GenericCollectionValue.Builder getValBuilder() {
        
        onChanged();
        return getValFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .cn.leancloud.play.proto.GenericCollectionValue val = 2;</code>
       */
      public cn.leancloud.play.proto.GenericCollectionValueOrBuilder getValOrBuilder() {
        if (valBuilder_ != null) {
          return valBuilder_.getMessageOrBuilder();
        } else {
          return val_ == null ?
              cn.leancloud.play.proto.GenericCollectionValue.getDefaultInstance() : val_;
        }
      }
      /**
       * <code>optional .cn.leancloud.play.proto.GenericCollectionValue val = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.leancloud.play.proto.GenericCollectionValue, cn.leancloud.play.proto.GenericCollectionValue.Builder, cn.leancloud.play.proto.GenericCollectionValueOrBuilder> 
          getValFieldBuilder() {
        if (valBuilder_ == null) {
          valBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.leancloud.play.proto.GenericCollectionValue, cn.leancloud.play.proto.GenericCollectionValue.Builder, cn.leancloud.play.proto.GenericCollectionValueOrBuilder>(
                  getVal(),
                  getParentForChildren(),
                  isClean());
          val_ = null;
        }
        return valBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:cn.leancloud.play.proto.GenericCollection.MapEntry)
    }

    // @@protoc_insertion_point(class_scope:cn.leancloud.play.proto.GenericCollection.MapEntry)
    private static final cn.leancloud.play.proto.GenericCollection.MapEntry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.leancloud.play.proto.GenericCollection.MapEntry();
    }

    public static cn.leancloud.play.proto.GenericCollection.MapEntry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MapEntry>
        PARSER = new com.google.protobuf.AbstractParser<MapEntry>() {
      public MapEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MapEntry(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MapEntry> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MapEntry> getParserForType() {
      return PARSER;
    }

    public cn.leancloud.play.proto.GenericCollection.MapEntry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int LIST_VALUE_FIELD_NUMBER = 1;
  private java.util.List<cn.leancloud.play.proto.GenericCollectionValue> listValue_;
  /**
   * <code>repeated .cn.leancloud.play.proto.GenericCollectionValue list_value = 1;</code>
   */
  public java.util.List<cn.leancloud.play.proto.GenericCollectionValue> getListValueList() {
    return listValue_;
  }
  /**
   * <code>repeated .cn.leancloud.play.proto.GenericCollectionValue list_value = 1;</code>
   */
  public java.util.List<? extends cn.leancloud.play.proto.GenericCollectionValueOrBuilder> 
      getListValueOrBuilderList() {
    return listValue_;
  }
  /**
   * <code>repeated .cn.leancloud.play.proto.GenericCollectionValue list_value = 1;</code>
   */
  public int getListValueCount() {
    return listValue_.size();
  }
  /**
   * <code>repeated .cn.leancloud.play.proto.GenericCollectionValue list_value = 1;</code>
   */
  public cn.leancloud.play.proto.GenericCollectionValue getListValue(int index) {
    return listValue_.get(index);
  }
  /**
   * <code>repeated .cn.leancloud.play.proto.GenericCollectionValue list_value = 1;</code>
   */
  public cn.leancloud.play.proto.GenericCollectionValueOrBuilder getListValueOrBuilder(
      int index) {
    return listValue_.get(index);
  }

  public static final int MAP_ENTRY_VALUE_FIELD_NUMBER = 2;
  private java.util.List<cn.leancloud.play.proto.GenericCollection.MapEntry> mapEntryValue_;
  /**
   * <code>repeated .cn.leancloud.play.proto.GenericCollection.MapEntry map_entry_value = 2;</code>
   */
  public java.util.List<cn.leancloud.play.proto.GenericCollection.MapEntry> getMapEntryValueList() {
    return mapEntryValue_;
  }
  /**
   * <code>repeated .cn.leancloud.play.proto.GenericCollection.MapEntry map_entry_value = 2;</code>
   */
  public java.util.List<? extends cn.leancloud.play.proto.GenericCollection.MapEntryOrBuilder> 
      getMapEntryValueOrBuilderList() {
    return mapEntryValue_;
  }
  /**
   * <code>repeated .cn.leancloud.play.proto.GenericCollection.MapEntry map_entry_value = 2;</code>
   */
  public int getMapEntryValueCount() {
    return mapEntryValue_.size();
  }
  /**
   * <code>repeated .cn.leancloud.play.proto.GenericCollection.MapEntry map_entry_value = 2;</code>
   */
  public cn.leancloud.play.proto.GenericCollection.MapEntry getMapEntryValue(int index) {
    return mapEntryValue_.get(index);
  }
  /**
   * <code>repeated .cn.leancloud.play.proto.GenericCollection.MapEntry map_entry_value = 2;</code>
   */
  public cn.leancloud.play.proto.GenericCollection.MapEntryOrBuilder getMapEntryValueOrBuilder(
      int index) {
    return mapEntryValue_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < listValue_.size(); i++) {
      output.writeMessage(1, listValue_.get(i));
    }
    for (int i = 0; i < mapEntryValue_.size(); i++) {
      output.writeMessage(2, mapEntryValue_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < listValue_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, listValue_.get(i));
    }
    for (int i = 0; i < mapEntryValue_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, mapEntryValue_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.leancloud.play.proto.GenericCollection)) {
      return super.equals(obj);
    }
    cn.leancloud.play.proto.GenericCollection other = (cn.leancloud.play.proto.GenericCollection) obj;

    boolean result = true;
    result = result && getListValueList()
        .equals(other.getListValueList());
    result = result && getMapEntryValueList()
        .equals(other.getMapEntryValueList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getListValueCount() > 0) {
      hash = (37 * hash) + LIST_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getListValueList().hashCode();
    }
    if (getMapEntryValueCount() > 0) {
      hash = (37 * hash) + MAP_ENTRY_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getMapEntryValueList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.leancloud.play.proto.GenericCollection parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.leancloud.play.proto.GenericCollection parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.leancloud.play.proto.GenericCollection parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.leancloud.play.proto.GenericCollection parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.leancloud.play.proto.GenericCollection parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.leancloud.play.proto.GenericCollection parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.leancloud.play.proto.GenericCollection parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.leancloud.play.proto.GenericCollection parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.leancloud.play.proto.GenericCollection parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.leancloud.play.proto.GenericCollection parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.leancloud.play.proto.GenericCollection prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cn.leancloud.play.proto.GenericCollection}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cn.leancloud.play.proto.GenericCollection)
      cn.leancloud.play.proto.GenericCollectionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.leancloud.play.proto.GenericCollectionOuterClass.internal_static_cn_leancloud_play_proto_GenericCollection_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.leancloud.play.proto.GenericCollectionOuterClass.internal_static_cn_leancloud_play_proto_GenericCollection_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.leancloud.play.proto.GenericCollection.class, cn.leancloud.play.proto.GenericCollection.Builder.class);
    }

    // Construct using cn.leancloud.play.proto.GenericCollection.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getListValueFieldBuilder();
        getMapEntryValueFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (listValueBuilder_ == null) {
        listValue_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        listValueBuilder_.clear();
      }
      if (mapEntryValueBuilder_ == null) {
        mapEntryValue_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        mapEntryValueBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.leancloud.play.proto.GenericCollectionOuterClass.internal_static_cn_leancloud_play_proto_GenericCollection_descriptor;
    }

    public cn.leancloud.play.proto.GenericCollection getDefaultInstanceForType() {
      return cn.leancloud.play.proto.GenericCollection.getDefaultInstance();
    }

    public cn.leancloud.play.proto.GenericCollection build() {
      cn.leancloud.play.proto.GenericCollection result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public cn.leancloud.play.proto.GenericCollection buildPartial() {
      cn.leancloud.play.proto.GenericCollection result = new cn.leancloud.play.proto.GenericCollection(this);
      int from_bitField0_ = bitField0_;
      if (listValueBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          listValue_ = java.util.Collections.unmodifiableList(listValue_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.listValue_ = listValue_;
      } else {
        result.listValue_ = listValueBuilder_.build();
      }
      if (mapEntryValueBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          mapEntryValue_ = java.util.Collections.unmodifiableList(mapEntryValue_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.mapEntryValue_ = mapEntryValue_;
      } else {
        result.mapEntryValue_ = mapEntryValueBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.leancloud.play.proto.GenericCollection) {
        return mergeFrom((cn.leancloud.play.proto.GenericCollection)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.leancloud.play.proto.GenericCollection other) {
      if (other == cn.leancloud.play.proto.GenericCollection.getDefaultInstance()) return this;
      if (listValueBuilder_ == null) {
        if (!other.listValue_.isEmpty()) {
          if (listValue_.isEmpty()) {
            listValue_ = other.listValue_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureListValueIsMutable();
            listValue_.addAll(other.listValue_);
          }
          onChanged();
        }
      } else {
        if (!other.listValue_.isEmpty()) {
          if (listValueBuilder_.isEmpty()) {
            listValueBuilder_.dispose();
            listValueBuilder_ = null;
            listValue_ = other.listValue_;
            bitField0_ = (bitField0_ & ~0x00000001);
            listValueBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getListValueFieldBuilder() : null;
          } else {
            listValueBuilder_.addAllMessages(other.listValue_);
          }
        }
      }
      if (mapEntryValueBuilder_ == null) {
        if (!other.mapEntryValue_.isEmpty()) {
          if (mapEntryValue_.isEmpty()) {
            mapEntryValue_ = other.mapEntryValue_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureMapEntryValueIsMutable();
            mapEntryValue_.addAll(other.mapEntryValue_);
          }
          onChanged();
        }
      } else {
        if (!other.mapEntryValue_.isEmpty()) {
          if (mapEntryValueBuilder_.isEmpty()) {
            mapEntryValueBuilder_.dispose();
            mapEntryValueBuilder_ = null;
            mapEntryValue_ = other.mapEntryValue_;
            bitField0_ = (bitField0_ & ~0x00000002);
            mapEntryValueBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMapEntryValueFieldBuilder() : null;
          } else {
            mapEntryValueBuilder_.addAllMessages(other.mapEntryValue_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cn.leancloud.play.proto.GenericCollection parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.leancloud.play.proto.GenericCollection) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<cn.leancloud.play.proto.GenericCollectionValue> listValue_ =
      java.util.Collections.emptyList();
    private void ensureListValueIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        listValue_ = new java.util.ArrayList<cn.leancloud.play.proto.GenericCollectionValue>(listValue_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        cn.leancloud.play.proto.GenericCollectionValue, cn.leancloud.play.proto.GenericCollectionValue.Builder, cn.leancloud.play.proto.GenericCollectionValueOrBuilder> listValueBuilder_;

    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollectionValue list_value = 1;</code>
     */
    public java.util.List<cn.leancloud.play.proto.GenericCollectionValue> getListValueList() {
      if (listValueBuilder_ == null) {
        return java.util.Collections.unmodifiableList(listValue_);
      } else {
        return listValueBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollectionValue list_value = 1;</code>
     */
    public int getListValueCount() {
      if (listValueBuilder_ == null) {
        return listValue_.size();
      } else {
        return listValueBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollectionValue list_value = 1;</code>
     */
    public cn.leancloud.play.proto.GenericCollectionValue getListValue(int index) {
      if (listValueBuilder_ == null) {
        return listValue_.get(index);
      } else {
        return listValueBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollectionValue list_value = 1;</code>
     */
    public Builder setListValue(
        int index, cn.leancloud.play.proto.GenericCollectionValue value) {
      if (listValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureListValueIsMutable();
        listValue_.set(index, value);
        onChanged();
      } else {
        listValueBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollectionValue list_value = 1;</code>
     */
    public Builder setListValue(
        int index, cn.leancloud.play.proto.GenericCollectionValue.Builder builderForValue) {
      if (listValueBuilder_ == null) {
        ensureListValueIsMutable();
        listValue_.set(index, builderForValue.build());
        onChanged();
      } else {
        listValueBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollectionValue list_value = 1;</code>
     */
    public Builder addListValue(cn.leancloud.play.proto.GenericCollectionValue value) {
      if (listValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureListValueIsMutable();
        listValue_.add(value);
        onChanged();
      } else {
        listValueBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollectionValue list_value = 1;</code>
     */
    public Builder addListValue(
        int index, cn.leancloud.play.proto.GenericCollectionValue value) {
      if (listValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureListValueIsMutable();
        listValue_.add(index, value);
        onChanged();
      } else {
        listValueBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollectionValue list_value = 1;</code>
     */
    public Builder addListValue(
        cn.leancloud.play.proto.GenericCollectionValue.Builder builderForValue) {
      if (listValueBuilder_ == null) {
        ensureListValueIsMutable();
        listValue_.add(builderForValue.build());
        onChanged();
      } else {
        listValueBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollectionValue list_value = 1;</code>
     */
    public Builder addListValue(
        int index, cn.leancloud.play.proto.GenericCollectionValue.Builder builderForValue) {
      if (listValueBuilder_ == null) {
        ensureListValueIsMutable();
        listValue_.add(index, builderForValue.build());
        onChanged();
      } else {
        listValueBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollectionValue list_value = 1;</code>
     */
    public Builder addAllListValue(
        java.lang.Iterable<? extends cn.leancloud.play.proto.GenericCollectionValue> values) {
      if (listValueBuilder_ == null) {
        ensureListValueIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, listValue_);
        onChanged();
      } else {
        listValueBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollectionValue list_value = 1;</code>
     */
    public Builder clearListValue() {
      if (listValueBuilder_ == null) {
        listValue_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        listValueBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollectionValue list_value = 1;</code>
     */
    public Builder removeListValue(int index) {
      if (listValueBuilder_ == null) {
        ensureListValueIsMutable();
        listValue_.remove(index);
        onChanged();
      } else {
        listValueBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollectionValue list_value = 1;</code>
     */
    public cn.leancloud.play.proto.GenericCollectionValue.Builder getListValueBuilder(
        int index) {
      return getListValueFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollectionValue list_value = 1;</code>
     */
    public cn.leancloud.play.proto.GenericCollectionValueOrBuilder getListValueOrBuilder(
        int index) {
      if (listValueBuilder_ == null) {
        return listValue_.get(index);  } else {
        return listValueBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollectionValue list_value = 1;</code>
     */
    public java.util.List<? extends cn.leancloud.play.proto.GenericCollectionValueOrBuilder> 
         getListValueOrBuilderList() {
      if (listValueBuilder_ != null) {
        return listValueBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(listValue_);
      }
    }
    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollectionValue list_value = 1;</code>
     */
    public cn.leancloud.play.proto.GenericCollectionValue.Builder addListValueBuilder() {
      return getListValueFieldBuilder().addBuilder(
          cn.leancloud.play.proto.GenericCollectionValue.getDefaultInstance());
    }
    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollectionValue list_value = 1;</code>
     */
    public cn.leancloud.play.proto.GenericCollectionValue.Builder addListValueBuilder(
        int index) {
      return getListValueFieldBuilder().addBuilder(
          index, cn.leancloud.play.proto.GenericCollectionValue.getDefaultInstance());
    }
    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollectionValue list_value = 1;</code>
     */
    public java.util.List<cn.leancloud.play.proto.GenericCollectionValue.Builder> 
         getListValueBuilderList() {
      return getListValueFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        cn.leancloud.play.proto.GenericCollectionValue, cn.leancloud.play.proto.GenericCollectionValue.Builder, cn.leancloud.play.proto.GenericCollectionValueOrBuilder> 
        getListValueFieldBuilder() {
      if (listValueBuilder_ == null) {
        listValueBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            cn.leancloud.play.proto.GenericCollectionValue, cn.leancloud.play.proto.GenericCollectionValue.Builder, cn.leancloud.play.proto.GenericCollectionValueOrBuilder>(
                listValue_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        listValue_ = null;
      }
      return listValueBuilder_;
    }

    private java.util.List<cn.leancloud.play.proto.GenericCollection.MapEntry> mapEntryValue_ =
      java.util.Collections.emptyList();
    private void ensureMapEntryValueIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        mapEntryValue_ = new java.util.ArrayList<cn.leancloud.play.proto.GenericCollection.MapEntry>(mapEntryValue_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        cn.leancloud.play.proto.GenericCollection.MapEntry, cn.leancloud.play.proto.GenericCollection.MapEntry.Builder, cn.leancloud.play.proto.GenericCollection.MapEntryOrBuilder> mapEntryValueBuilder_;

    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollection.MapEntry map_entry_value = 2;</code>
     */
    public java.util.List<cn.leancloud.play.proto.GenericCollection.MapEntry> getMapEntryValueList() {
      if (mapEntryValueBuilder_ == null) {
        return java.util.Collections.unmodifiableList(mapEntryValue_);
      } else {
        return mapEntryValueBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollection.MapEntry map_entry_value = 2;</code>
     */
    public int getMapEntryValueCount() {
      if (mapEntryValueBuilder_ == null) {
        return mapEntryValue_.size();
      } else {
        return mapEntryValueBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollection.MapEntry map_entry_value = 2;</code>
     */
    public cn.leancloud.play.proto.GenericCollection.MapEntry getMapEntryValue(int index) {
      if (mapEntryValueBuilder_ == null) {
        return mapEntryValue_.get(index);
      } else {
        return mapEntryValueBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollection.MapEntry map_entry_value = 2;</code>
     */
    public Builder setMapEntryValue(
        int index, cn.leancloud.play.proto.GenericCollection.MapEntry value) {
      if (mapEntryValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMapEntryValueIsMutable();
        mapEntryValue_.set(index, value);
        onChanged();
      } else {
        mapEntryValueBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollection.MapEntry map_entry_value = 2;</code>
     */
    public Builder setMapEntryValue(
        int index, cn.leancloud.play.proto.GenericCollection.MapEntry.Builder builderForValue) {
      if (mapEntryValueBuilder_ == null) {
        ensureMapEntryValueIsMutable();
        mapEntryValue_.set(index, builderForValue.build());
        onChanged();
      } else {
        mapEntryValueBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollection.MapEntry map_entry_value = 2;</code>
     */
    public Builder addMapEntryValue(cn.leancloud.play.proto.GenericCollection.MapEntry value) {
      if (mapEntryValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMapEntryValueIsMutable();
        mapEntryValue_.add(value);
        onChanged();
      } else {
        mapEntryValueBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollection.MapEntry map_entry_value = 2;</code>
     */
    public Builder addMapEntryValue(
        int index, cn.leancloud.play.proto.GenericCollection.MapEntry value) {
      if (mapEntryValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMapEntryValueIsMutable();
        mapEntryValue_.add(index, value);
        onChanged();
      } else {
        mapEntryValueBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollection.MapEntry map_entry_value = 2;</code>
     */
    public Builder addMapEntryValue(
        cn.leancloud.play.proto.GenericCollection.MapEntry.Builder builderForValue) {
      if (mapEntryValueBuilder_ == null) {
        ensureMapEntryValueIsMutable();
        mapEntryValue_.add(builderForValue.build());
        onChanged();
      } else {
        mapEntryValueBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollection.MapEntry map_entry_value = 2;</code>
     */
    public Builder addMapEntryValue(
        int index, cn.leancloud.play.proto.GenericCollection.MapEntry.Builder builderForValue) {
      if (mapEntryValueBuilder_ == null) {
        ensureMapEntryValueIsMutable();
        mapEntryValue_.add(index, builderForValue.build());
        onChanged();
      } else {
        mapEntryValueBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollection.MapEntry map_entry_value = 2;</code>
     */
    public Builder addAllMapEntryValue(
        java.lang.Iterable<? extends cn.leancloud.play.proto.GenericCollection.MapEntry> values) {
      if (mapEntryValueBuilder_ == null) {
        ensureMapEntryValueIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, mapEntryValue_);
        onChanged();
      } else {
        mapEntryValueBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollection.MapEntry map_entry_value = 2;</code>
     */
    public Builder clearMapEntryValue() {
      if (mapEntryValueBuilder_ == null) {
        mapEntryValue_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        mapEntryValueBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollection.MapEntry map_entry_value = 2;</code>
     */
    public Builder removeMapEntryValue(int index) {
      if (mapEntryValueBuilder_ == null) {
        ensureMapEntryValueIsMutable();
        mapEntryValue_.remove(index);
        onChanged();
      } else {
        mapEntryValueBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollection.MapEntry map_entry_value = 2;</code>
     */
    public cn.leancloud.play.proto.GenericCollection.MapEntry.Builder getMapEntryValueBuilder(
        int index) {
      return getMapEntryValueFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollection.MapEntry map_entry_value = 2;</code>
     */
    public cn.leancloud.play.proto.GenericCollection.MapEntryOrBuilder getMapEntryValueOrBuilder(
        int index) {
      if (mapEntryValueBuilder_ == null) {
        return mapEntryValue_.get(index);  } else {
        return mapEntryValueBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollection.MapEntry map_entry_value = 2;</code>
     */
    public java.util.List<? extends cn.leancloud.play.proto.GenericCollection.MapEntryOrBuilder> 
         getMapEntryValueOrBuilderList() {
      if (mapEntryValueBuilder_ != null) {
        return mapEntryValueBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(mapEntryValue_);
      }
    }
    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollection.MapEntry map_entry_value = 2;</code>
     */
    public cn.leancloud.play.proto.GenericCollection.MapEntry.Builder addMapEntryValueBuilder() {
      return getMapEntryValueFieldBuilder().addBuilder(
          cn.leancloud.play.proto.GenericCollection.MapEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollection.MapEntry map_entry_value = 2;</code>
     */
    public cn.leancloud.play.proto.GenericCollection.MapEntry.Builder addMapEntryValueBuilder(
        int index) {
      return getMapEntryValueFieldBuilder().addBuilder(
          index, cn.leancloud.play.proto.GenericCollection.MapEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .cn.leancloud.play.proto.GenericCollection.MapEntry map_entry_value = 2;</code>
     */
    public java.util.List<cn.leancloud.play.proto.GenericCollection.MapEntry.Builder> 
         getMapEntryValueBuilderList() {
      return getMapEntryValueFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        cn.leancloud.play.proto.GenericCollection.MapEntry, cn.leancloud.play.proto.GenericCollection.MapEntry.Builder, cn.leancloud.play.proto.GenericCollection.MapEntryOrBuilder> 
        getMapEntryValueFieldBuilder() {
      if (mapEntryValueBuilder_ == null) {
        mapEntryValueBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            cn.leancloud.play.proto.GenericCollection.MapEntry, cn.leancloud.play.proto.GenericCollection.MapEntry.Builder, cn.leancloud.play.proto.GenericCollection.MapEntryOrBuilder>(
                mapEntryValue_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        mapEntryValue_ = null;
      }
      return mapEntryValueBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:cn.leancloud.play.proto.GenericCollection)
  }

  // @@protoc_insertion_point(class_scope:cn.leancloud.play.proto.GenericCollection)
  private static final cn.leancloud.play.proto.GenericCollection DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.leancloud.play.proto.GenericCollection();
  }

  public static cn.leancloud.play.proto.GenericCollection getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GenericCollection>
      PARSER = new com.google.protobuf.AbstractParser<GenericCollection>() {
    public GenericCollection parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new GenericCollection(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GenericCollection> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GenericCollection> getParserForType() {
    return PARSER;
  }

  public cn.leancloud.play.proto.GenericCollection getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

