// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: generic_collection.proto

package cn.leancloud.play.proto;

public interface GenericCollectionValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.leancloud.play.proto.GenericCollectionValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .cn.leancloud.play.proto.GenericCollectionValue.Type type = 1;</code>
   */
  int getTypeValue();
  /**
   * <code>optional .cn.leancloud.play.proto.GenericCollectionValue.Type type = 1;</code>
   */
  cn.leancloud.play.proto.GenericCollectionValue.Type getType();

  /**
   * <code>optional int32 int_value = 2;</code>
   */
  int getIntValue();

  /**
   * <code>optional int64 long_int_value = 3;</code>
   */
  long getLongIntValue();

  /**
   * <code>optional bool bool_value = 4;</code>
   */
  boolean getBoolValue();

  /**
   * <code>optional string string_value = 5;</code>
   */
  java.lang.String getStringValue();
  /**
   * <code>optional string string_value = 5;</code>
   */
  com.google.protobuf.ByteString
      getStringValueBytes();

  /**
   * <code>optional bytes bytes_value = 6;</code>
   */
  com.google.protobuf.ByteString getBytesValue();

  /**
   * <code>optional float float_value = 7;</code>
   */
  float getFloatValue();

  /**
   * <code>optional double double_value = 8;</code>
   */
  double getDoubleValue();

  /**
   * <code>optional int32 object_type_id = 9;</code>
   */
  int getObjectTypeId();

  public cn.leancloud.play.proto.GenericCollectionValue.ValueCase getValueCase();
}
