// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: generic_collection.proto

package cn.leancloud.play.proto;

public interface GenericCollectionValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.leancloud.play.proto.GenericCollectionValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .cn.leancloud.play.proto.GenericCollectionValue.Type type = 1;</code>
   */
  int getTypeValue();
  /**
   * <code>optional .cn.leancloud.play.proto.GenericCollectionValue.Type type = 1;</code>
   */
  cn.leancloud.play.proto.GenericCollectionValue.Type getType();

  /**
   * <code>optional int32 intValue = 2;</code>
   */
  int getIntValue();

  /**
   * <code>optional int64 longIntValue = 3;</code>
   */
  long getLongIntValue();

  /**
   * <code>optional bool boolValue = 4;</code>
   */
  boolean getBoolValue();

  /**
   * <code>optional string stringValue = 5;</code>
   */
  java.lang.String getStringValue();
  /**
   * <code>optional string stringValue = 5;</code>
   */
  com.google.protobuf.ByteString
      getStringValueBytes();

  /**
   * <code>optional bytes bytesValue = 6;</code>
   */
  com.google.protobuf.ByteString getBytesValue();

  /**
   * <code>optional float floatValue = 7;</code>
   */
  float getFloatValue();

  /**
   * <code>optional double doubleValue = 8;</code>
   */
  double getDoubleValue();

  public cn.leancloud.play.proto.GenericCollectionValue.ValueCase getValueCase();
}
